//
// ===========================================================================
//
//                            PUBLIC DOMAIN NOTICE
//               National Center for Biotechnology Information
//
//  This software/database is a "United States Government Work" under the
//  terms of the United States Copyright Act.  It was written as part of
//  the author's official duties as a United States Government employee and
//  thus cannot be copyrighted.  This software/database is freely available
//  to the public for use. The National Library of Medicine and the U.S.
//  Government have not placed any restriction on its use or reproduction.
//
//  Although all reasonable efforts have been taken to ensure the accuracy
//  and reliability of the software and data, the NLM and the U.S.
//  Government do not and cannot warrant the performance or results that
//  may be obtained by using this software or data. The NLM and the U.S.
//  Government disclaim all warranties, express or implied, including
//  warranties of performance, merchantability or fitness for any particular
//  purpose.
//
//  Please cite the author in any work or product based on this material.
//
// ===========================================================================
//
// Code authors:  Aleksandar Stojmirovic, Alexander Bliskovsky
//

package gov.nih.nlm.ncbi.qmbp.cytosaddlesum.main;

/**
 *
 * @author aleksand
 */
public class AboutDialog extends javax.swing.JDialog {

    /** Creates new form AboutDialog */
    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bannerLabel = new javax.swing.JLabel();
        qmbpLabel = new javax.swing.JLabel();
        ncbiLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About CytoSaddleSum");
        setMinimumSize(new java.awt.Dimension(0, 540));
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        bannerLabel.setBackground(new java.awt.Color(51, 51, 51));
        bannerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/nih/nlm/ncbi/qmbp/cytosaddlesum/resources/banner-saddlesum.png"))); // NOI18N
        bannerLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        bannerLabel.setOpaque(true);
        bannerLabel.setPreferredSize(new java.awt.Dimension(465, 77));

        qmbpLabel.setBackground(new java.awt.Color(255, 255, 255));
        qmbpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/nih/nlm/ncbi/qmbp/cytosaddlesum/resources/logo-qmbp4.png"))); // NOI18N
        qmbpLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        qmbpLabel.setOpaque(true);

        ncbiLabel.setBackground(new java.awt.Color(255, 255, 255));
        ncbiLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/nih/nlm/ncbi/qmbp/cytosaddlesum/resources/logo-ncbi4.png"))); // NOI18N
        ncbiLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        ncbiLabel.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14));
        jLabel1.setText("<html><i>CytoSaddleSum</i> provides <i>Cytoscape</i> users with access to the functionality of <i>SaddleSum</i>,\na functional enrichment tool based on sum-of-weight scores. \nIt operates by querying <i>SaddleSum</i> locally (using the\nstandalone version) or remotely (through an HTTP request to a web server). The\n functional enrichment results are shown as a term relationship\nnetwork, where nodes represent terms and edges show term\nrelationships. Furhtermore, query results are written as <i>Cytoscape</i> attributes\nallowing easy saving, retrieval and integration into network-based data analysis workflows.</html>\n");
        jLabel1.setInheritsPopupMenu(false);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24));
        jLabel2.setText("<html><b><i>CytoSaddleSum</i>: a functional enrichment analysis plugin for <i>Cytoscape</i> based on sum-of-weights scores</b></html>");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14));
        jLabel3.setText("<html><b>Authors:</b> Aleksandar Stojmirovic, Alexander Bliskovsky and Yi-Kuo Yu<br><br>\nNational Center for Biotechnology Information, National Library of Medicine, National Institutes of Health,<br> Bethesda, MD 20894, United States<br><br>\n<b>Documentation:</b> <a href=\"http://www.ncbi.nlm.nih.gov/CBBresearch/Yu/mn/enrich/doc/documentation.html\"> http://www.ncbi.nlm.nih.gov/CBBresearch/Yu/mn/enrich/doc/documentation.html </a><br>\n<b>Downloads:</b> <a href=\"http://www.ncbi.nlm.nih.gov/CBBresearch/qmbp/Yu/downloads\"> http://www.ncbi.nlm.nih.gov/CBBresearch/Yu/downloads</a><br>\n<b>References:</b><br>\nA. Stojmirovic and Y.-K. Yu. <a href=\"http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2958744/\">Robust and accurate data enrichment\nstatistics via distribution function of sum of weights.</a><br>\n<em>Bioinformatics</em>, <strong>26</strong> (21):2752-2759, 2010.</li>\n<br><br>\nThe source code is placed in Public Domain.\n</html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(qmbpLabel)
                .addGap(0, 0, 0)
                .addComponent(bannerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ncbiLabel))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qmbpLabel)
                    .addComponent(bannerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ncbiLabel))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                AboutDialog dialog = new AboutDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bannerLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel ncbiLabel;
    private javax.swing.JLabel qmbpLabel;
    // End of variables declaration//GEN-END:variables
}
